name: livetoura
description: Real-time community sports tournament tracking mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.1.0
  # Firebase packages temporarily removed for Sprint-2 web demo
  # firebase_core: ^2.24.0
  # firebase_auth: ^4.10.0
  # cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Asset declarations for static resources
  assets:
    - assets/demo/
